spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: skillbox
    password: skillbox





  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/db-changelog-master.xml
    default-schema: public

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: public

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: skillbox

topic:
  names:
    notify: notification
    message: message

jwt:
  secret:
    access: jwtsocialserviceapptywrtywryhwsrtyhsfthshsrhsrth
    refresh: jwtsocialsirviceapprefreshtokenstrhsrthhtrstthsrhsh

whitelist:
  permit:
    - /**/login
    - /**/post/**
    - /**/captcha
    - /**/register
    - /**/registration
    - /**/v3/api-docs/**
    - /**/swagger-ui/**
    - /**/storage
    - /**/change-password/**

cloudinary:
  cloud_name: dv7luy20w
  api_key: 658913949174425
  api_secret: L9cseajDW8sgMGRVl0-oLXTMPmE
  defaultPhoto: https://res.cloudinary.com/dv7luy20w/image/upload/v1678120930/avatar_v4ylx1.png

mail:
  host: smtp.yandex.ru
  username: javapro.team33@yandex.ru
  password: ilhndcznpjohmzbm
  port: 465
  protocol: smtps
  debug: true
  url: localhost:8097





